JuCheap.Web/Areas/Adm/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using JuCheap.Core;
using JuCheap.Core.Extentions;
using JuCheap.Service.Abstracts;
using JuCheap.Service.Dto;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace JuCheap.Web.Areas.Adm.Controllers
{
    /// <summary>
    /// user
    /// </summary>
    public class UserController : AdmBaseController
    {
        public IUserRoleService userRoleService { get; set; }

        

        #region Page

        // GET: Adm/User
        public ActionResult Index(string moudleId, string menuId, string btnId)
        {
            GetButtons(menuId);
            return View();
        }

        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
        public ActionResult Add(string moudleId, string menuId, string btnId)
        {
            return View();
        }

        public ActionResult Edit(string moudleId, string menuId, string btnId, string id)
        {
            var model = userService.GetOne(item => item.Id == id);
            return View(model);
        }

        /// <summary>
        /// 用户角色授权
        /// </summary>
        /// <param name="moudleId"></param>
        /// <param name="menuId"></param>
        /// <param name="btnId"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Authen(string moudleId, string menuId, string btnId, string id)
        {
            return View();
        }

        // GET: Adm/User/Login
        [HttpGet, AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        /// <summary>
        /// 忘记密码
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult ForgotPwd()
        {
            return View();
        }

        /// <summary>
        /// 注册
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Reg()
        {
            return View();
        }

        /// <summary>
        /// 注销
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                userService.Logout();
            }
            return RedirectToAction("Login");
        }

        #endregion

        #region Ajax

        [HttpGet]
        public JsonResult GetList(string moudleId, string menuId, string btnId)
        {
            var queryBase = new QueryBase
            {
                Start = Request["start"].ToInt(),
                Length = Request["length"].ToInt(),
                Draw = Request["draw"].ToInt(),
                SearchKey = Request["keywords"]
            };
            Expression<Func<UserDto, bool>> exp = item => !item.IsDeleted;
            if (!queryBase.SearchKey.IsBlank())
                exp = exp.And(item => item.LoginName.Contains(queryBase.SearchKey) || item.RealName.Contains(queryBase.SearchKey));

            var dto = userService.GetWithPages(queryBase, exp, Request["orderBy"], Request["orderDir"]);
            var res = new ResultDto<UserDto>
            {
                start = dto.start,
                length = dto.length,
                recordsTotal = dto.recordsTotal,
                data = dto.data.Select(d => new UserDto
                {
                    Id = d.Id,
                    LoginName = d.LoginName,
                    RealName = d.RealName,
                    Email = d.Email,
                    CreateDateTime = d.CreateDateTime,
                    Status = d.Status,
                    IsDeleted = d.IsDeleted
                }).ToList()
            };
            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetMyRoles(string moudleId, string menuId, string btnId, string id)
        {
            var queryBase = new QueryBase
            {
                Start = Request["start"].ToInt(),
                Length = Request["length"].ToInt(),
                Draw = Request["draw"].ToInt(),
                SearchKey = Request["keywords"]
            };

            var dto = userService.GetMyRoles(queryBase, id);
            return Json(dto, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetNotMyRoles(string moudleId, string menuId, string btnId, string id)
        {
            var queryBase = new QueryBase
            {
                Start = Request["start"].ToInt(),
                Length = Request["length"].ToInt(),
                Draw = Request["draw"].ToInt(),
                SearchKey = Request["keywords"]
            };

            var dto = userService.GetNotMyRoles(queryBase, id);
            return Json(dto, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AuthenRole(string moudleId, string menuId, string btnId, string id, List<RoleDto> roles)
        {
            var dto = new Result<string>();
            var userRoles = roles.Select(item => new UserRoleDto {UserId = id, RoleId = item.Id}).ToList();
            dto.flag = userRoleService.Add(userRoles);
            return Json(dto, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UnAuthenRole(string moudleId, string menuId, string btnId, string id, List<RoleDto> roles)
        {
            var dto = new Result<string>();
            var roleIds = roles.Select(item => item.Id);
            dto.flag = userRoleService.DeleteReal(item => roleIds.Contains(item.RoleId));
            return Json(dto, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 登录
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost, AllowAnonymous]
        public ActionResult Login(UserDto model)
        {
            var result = userService.Login(model);
            if (result.flag)
            {
                var authenticationManager = HttpContext.GetOwinContext().Authentication;
                var claims = new List<Claim>
                {
                    new Claim(ConstValue.LoginUserIdKey, result.data.Id),
                    new Claim(ClaimTypes.Name, model.LoginName)
                };
                var identity = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);
                var pro = new AuthenticationProperties()
                {
                    IsPersistent = true
                };
                authenticationManager.SignIn(pro, identity);
                return RedirectToAction("Index", "Control");
            }
            ModelState.AddModelError("Error", result.msg);
            return View();
        }



        [HttpPost]
        public ActionResult Add(string moudleId, string menuId, string btnId, UserDto dto)
        {
            dto.Password = dto.Password.ToMD5();
            userService.Add(dto);
            return RedirectToAction("Index", RouteData.Values);
        }


        [HttpPost]
        public ActionResult Edit(string moudleId, string menuId, string btnId, UserDto dto)
        {
            var old = userService.GetOne(item => item.Id == dto.Id);
            dto.Password = dto.Password.IsBlank() ? old.Password : dto.Password.ToMD5();
            dto.LoginName = old.LoginName;
            userService.Update(dto);
            return RedirectToAction("Index", RouteData.Values);
        }


        [HttpPost]
        public JsonResult Delete(string moudleId, string menuId, string btnId, List<string> ids)
        {
            var res = new Result<string>();

            if (ids != null && ids.Any())
                res.flag = userService.Delete(item => ids.Contains(item.Id));

            return Json(res, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public JsonResult GetTestData()
        {
            List<UserDto> users = new List<UserDto>();
            for (int i = 0; i < 5; i++)
            {
                users.Add(new UserDto()
                {
                    LoginName = "i" + i,
                    Id = i.ToString()
                });
            }
            return Json(users, JsonRequestBehavior.AllowGet);
        }

        #endregion
    }
}

JuCheap.Web/Areas/Adm/Views/User/Add.cshtml
@model JuCheap.Service.Dto.UserDto
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Adm/Views/Shared/_Layout_Body.cshtml";
}

@section Scripts{
    <script>
        $("#submitForm").validate({
            submitHandler: jucheap.buttonLoading,
            rules: {
                LoginName: {
                    required: true,
                    minlength: 5,
                    maxlength: 20
                },
                Email: {
                    required: true,
                    minlength: 5,
                    maxlength: 36,
                    email:true
                },
                RealName: {
                    required: true,
                    minlength: 2,
                    maxlength: 20
                },
                Password: {
                    required: true,
                    minlength: 6,
                    maxlength: 36
                }
            },
            messages: {
                LoginName: {
                    required: "请输入登录账号",
                    minlength: "最小长度为5个字符",
                    maxlength: "最大长度为20个字符"
                },
                Email: {
                    required: "请输入注册邮箱",
                    minlength: "最小长度为6个字符",
                    maxlength: "最大长度为36个字符",
                    email: "请输入正确的邮箱地址"
                },
                RealName: {
                    required: "请输入真实姓名",
                    minlength: "最小长度为2个字符",
                    maxlength: "最大长度为20个字符"
                },
                Password: {
                    required: "请输入登录密码",
                    minlength: "最小长度为6个字符",
                    maxlength: "最大长度为36个字符"
                }
            }
        });
    </script>
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                添加用户
            </header>
            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form" id="submitForm" method="POST" action="@Request.Url.PathAndQuery" novalidate="novalidate">
                        <div class="form-group ">
                            @Html.LabelFor(item => item.LoginName, new {@class = "control-label col-lg-2"})
                            <div class="col-lg-10">
                                @Html.TextBoxFor(item => item.LoginName, new {@class = "form-control"})
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.Email, new {@class = "control-label col-lg-2"})
                            <div class="col-lg-10">
                                @Html.TextBoxFor(item => item.Email, new {@class = "form-control"})
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.RealName, new {@class = "control-label col-lg-2"})
                            <div class="col-lg-10">
                                @Html.TextBoxFor(item => item.RealName, new {@class = "form-control"})
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.Password, new {@class = "control-label col-lg-2"})
                            <div class="col-lg-10">
                                @Html.PasswordFor(item => item.Password, new {@class = "form-control"})
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.Status, new {@class = "control-label col-lg-2"})
                            <div class="col-lg-10">
                                @Html.EnumDropDownListFor(item => item.Status, new {@class = "form-control"})
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-success" type="submit">保存</button>
                                <button class="btn btn-default" type="button" onclick="jucheap.goback(this)">返回</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>

JuCheap.Web/Areas/Adm/Views/User/Authen.cshtml
@{
    Layout = "/Areas/Adm/Views/Shared/_Layout_Body.cshtml";
}
@section StylesBefore{
    @Styles.Render("~/Template/Admin/jucheap/Css/DataTable")
}
@section Scripts{
    @Scripts.Render("~/JS/Admin/jucheap/DataTable")

    <script>
        var grid = null;
        var mygrid = null;

        function reload() {
            grid.reload();
        }

        function authenRole(action) {
            var url = '@Url.Action("AuthenRole", ViewContext.RouteData.Values)';
            var rows = grid.getSelectedRows();
            if (action == "unauthen") {
                url = '@Url.Action("UnAuthenRole", ViewContext.RouteData.Values)';
                rows = mygrid.getSelectedRows();
            }
            var actionName = action == "unauthen" ? "取消" : "授权";
            
            if (rows != null && rows.length > 0) {
                $.ajax({
                    url: url,
                    type: 'post',
                    data: JSON.stringify(rows),
                    dataType: 'json',
                    contentType: 'application/json',
                    success: function(res) {
                        if (res.flag) {
                            parent.layer.alert(actionName + "成功");
                            grid.reload();
                            mygrid.reload();
                        } else {
                            parent.layer.alert(actionName + "失败:" + res.msg);
                        }
                    }
                });
            } else {
                parent.layer.alert("请选择要" + actionName + "的角色");
            }
        }

        $(function() {
            var cols = [
                { data: "Id", name: "Id", orderable: false },
                { data: "Name", name: "Name", orderable: true }
            ];
            var config = {
                id: "table_server",
                url: "@Url.Action("GetNotMyRoles", @ViewContext.RouteData.Values)",
                columns: cols,
                order: [[1, "desc"]]
            };
            grid = new jucheap.grid(config);
            grid.load();

            $(".box-refresh").click(function() {
                grid.reload();
            });

            var myconfig = {
                id: "table_server_my",
                url: "@Url.Action("GetMyRoles", @ViewContext.RouteData.Values)",
                columns: cols,
                order: [[1, "desc"]],
                canFilter: false
            };
            mygrid = new jucheap.grid(myconfig);
            mygrid.load();
        });
    </script>
}
<div class="row">
    <div class="col-md-5">
        <section class="panel">
            <header class="panel-heading" style="margin-bottom: 10px;">
               我拥有的角色
                <span class="tools pull-right">
                    <a class="fa fa-repeat box-refresh" href="javascript:;"></a>
                    <a class="t-close fa fa-times" href="javascript:;"></a>
                </span>
            </header>
            <table id="table_server_my" class="table responsive-data-table data-table table-hover">
                <thead>
                    <tr>
                        <th style="width: 40px;">
                            选择
                        </th>
                        <th>
                            角色名称
                        </th>
                    </tr>
                </thead>
            </table>
        </section>
    </div>

    <div class="col-md-2 text-center">
        <p>
            <button class="btn btn-primary" onclick="authenRole('authen')">&lt;&lt;授权</button>
        </p>
        <p>
            <button class="btn btn-success" onclick="authenRole('unauthen')">取消&gt;&gt;</button>
        </p>
    </div>

    <div class="col-md-5">
        <div class="hidden" id="hidden_filter">
            @* 把需要搜索的条件放到hidden里面，在table格式化完成的时候直接调用$.html()赋值，免去了在js拼接标签的麻烦 *@
            <div class="row" style="margin-right:0;">
                <form class="form-inline" role="form">
                    <div class="form-group">
                        <label class="sr-only" for="keywords">关键字</label>
                        <input type="text" class="form-control" id="keywords" name="keywords" placeholder="角色名称" maxlength="20" />
                    </div>
                    <button type="button" class="btn btn-success" name="go_search">搜索</button>
                </form>
            </div>
        </div>
        <section class="panel">
            <header class="panel-heading" style="margin-bottom: 10px;">
                尚未拥有的角色
                <span class="tools pull-right">
                    <a class="fa fa-repeat box-refresh" href="javascript:;"></a>
                    <a class="t-close fa fa-times" href="javascript:;"></a>
                </span>
            </header>
            <table id="table_server" class="table responsive-data-table data-table table-hover">
                <thead>
                    <tr>
                        <th style="width: 40px;">
                            选择
                        </th>
                        <th>
                            角色名称
                        </th>
                    </tr>
                </thead>
            </table>
        </section>
    </div>
</div>

JuCheap.Web/Areas/Adm/Views/User/Edit.cshtml
@model JuCheap.Service.Dto.UserDto
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Adm/Views/Shared/_Layout_Body.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                编辑用户
            </header>
            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form" id="submitForm" method="POST" action="@Request.Url.PathAndQuery" novalidate="novalidate">
                        @Html.HiddenFor(item => item.Id, new { @class = "form-control" })
                        <div class="form-group ">
                            @Html.LabelFor(item => item.LoginName, new { @class = "control-label col-lg-2" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(item => item.LoginName, new { @class = "form-control", disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.Email, new { @class = "control-label col-lg-2" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(item => item.Email, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.RealName, new { @class = "control-label col-lg-2" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(item => item.RealName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.Password, new { @class = "control-label col-lg-2" })
                            <div class="col-lg-10">
                                @Html.PasswordFor(item => item.Password, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(item => item.Status, new { @class = "control-label col-lg-2" })
                            <div class="col-lg-10">
                                @Html.EnumDropDownListFor(item => item.Status, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-success" type="submit">保存</button>
                                <button class="btn btn-default" type="button" onclick="jucheap.goback(this)">返回</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>

@section Scripts{
    <script>
        $("#submitForm").validate({
            submitHandler: jucheap.buttonLoading,
            rules: {
                LoginName: {
                    required: true,
                    minlength: 5,
                    maxlength: 20
                },
                Email: {
                    required: true,
                    minlength: 5,
                    maxlength: 36,
                    email:true
                },
                RealName: {
                    required: true,
                    minlength: 2,
                    maxlength: 20
                }
            },
            messages: {
                LoginName: {
                    required: "请输入登录账号",
                    minlength: "最小长度为5个字符",
                    maxlength: "最大长度为20个字符"
                },
                Email: {
                    required: "请输入注册邮箱",
                    minlength: "最小长度为6个字符",
                    maxlength: "最大长度为36个字符",
                    email: "请输入正确的邮箱地址"
                },
                RealName: {
                    required: "请输入真实姓名",
                    minlength: "最小长度为2个字符",
                    maxlength: "最大长度为20个字符"
                }
            }
        });
    </script>
}

JuCheap.Web/Areas/Adm/Views/User/ForgotPwd.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

JuCheap.Web/Areas/Adm/Views/User/Index.cshtml
@using System.Text
@using JuCheap.Service.Dto

@{
    Layout = "/Areas/Adm/Views/Shared/_Layout_Body.cshtml";
}
@section StylesBefore{
@Styles.Render("~/Template/Admin/jucheap/Css/DataTable")
}
@section Scripts{
    @Scripts.Render("~/JS/Admin/jucheap/DataTable")

    <script>
        var grid = null;
        function reload() {
            $("#go_search").trigger("click");
        }

        $(function() {
            var cols = [
                { data: "Id", orderable: false },
                { data: "LoginName", name: "LoginName", orderable: true },
                { data: "RealName", name: "RealName", orderable: true },
                { data: "Email", name: "Email", orderable: true },
                { data: function (e) { return e.StatusName; }, name: "Status", orderable: true },
                {
                    data: function(e) {
                        return e.CreateDateTime.toString().getDate();
                    }, name: "CreateDateTime",
                    orderable: true
                }
            ];
            var config = {
                id: "table_server",
                url: "@Url.Action("GetList",@ViewContext.RouteData.Values)",
                columns: cols,
                order: [[5, "desc"]]
            };
            grid = new jucheap.grid(config);
            grid.load();

            $(".box-refresh").click(function() {
                grid.reload();
            });
        });
    </script>
}

<div class="row">
    <div class="col-lg-12">
        <div class="hidden" id="hidden_filter">
            @* 把需要搜索的条件放到hidden里面，在table格式化完成的时候直接调用$.html()赋值，免去了在js拼接标签的麻烦 *@
            <div class="row" style="margin-right:0;">
                <form class="form-inline" role="form">
                    <div class="form-group">
                        <label class="sr-only" for="keywords">关键字</label>
                        <input type="text" class="form-control" id="keywords" name="keywords" placeholder="登陆名/真实名" maxlength="20" />
                    </div>
                    <button type="button" class="btn btn-success" name="go_search">搜索</button>
                </form>
            </div>
        </div>
        <section class="panel">
            <header class="panel-heading" style="margin-bottom: 10px;">
                &nbsp;
                <span class="tools pull-left">
                    @if (ViewBag.MyButtons != null)
                    {
                        List<MenuDto> btns = ViewBag.MyButtons;
                        StringBuilder sb = new StringBuilder();
                        foreach (var btn in btns)
                        {
                            sb.AppendFormat("<button type=\"button\" class=\"btn btn-success m-b-10\" onclick=\"jucheap.goAction(this,  '{0}', '{1}','{2}', '{3}',grid)\">{4}</button>&nbsp;&nbsp;", ViewContext.RouteData.Values["moudleId"], btn.ParentId, btn.Id, btn.Url, btn.Name);
                        }
                        @(new MvcHtmlString(sb.ToString()))
                    }
                </span>
                <span class="tools pull-right">
                    <a class="fa fa-repeat box-refresh" href="javascript:;"></a>
                    <a class="t-close fa fa-times" href="javascript:;"></a>
                </span>
            </header>
            <table id="table_server" class="table responsive-data-table data-table table-hover">
                <thead>
                    <tr>
                        <th style="width: 40px;">
                            选择
                        </th>
                        <th>
                            账号
                        </th>
                        <th>
                            姓名
                        </th>
                        <th>
                            邮箱
                        </th>
                        <th>
                            状态
                        </th>
                        <th>
                            创建日期
                        </th>
                    </tr>
                </thead>
            </table>
        </section>
    </div>

</div>

JuCheap.Web/Areas/Adm/Views/User/Login.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="JuCheap"/>
    <meta name="keywords" content="JuCheap admin dashboard, admin, flat, flat ui, ui kit, app, web app, responsive"/>
    <link rel="shortcut icon" href="/Images/ico/favicon.ico"/>
    <title>Login - JuCheap</title>
    <!--common style-->
    @Styles.Render("~/Template/Admin/jucheap/Css/BaseStyles")
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    @Html.Partial("BaiduTongji")
</head>

<body class="login-body">

    <div class="login-logo">
        JuCheap
    </div>

    <h2 class="form-heading">登录</h2>
    <div class="container log-row">
        <form id="loginForm" class="form-signin" action="@Url.Action("Login", "User")" method="POST">
            <div class="login-wrap">
                @{
                    if (!ViewData.ModelState.IsValid)
                    {
                        <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            @string.Format("登录失败：{0}", ViewData.ModelState["Error"].Errors[0].ErrorMessage)
                        </div>
                    }
                }
                <input type="text" id="LoginName" name="LoginName" class="form-control" placeholder="账号" value="admin" required autofocus/>
                <input type="password" id="Password" name="Password" class="form-control" placeholder="密码" value="qwaszx" required/>


                <button class="btn btn-lg btn-success btn-block" type="submit">登录</button>
                <label class="checkbox-custom check-success">
                    <input type="checkbox" value="remember-me" id="checkbox1"> <label for="checkbox1">记住我</label>
                    <a class="pull-right" data-toggle="modal" href="@Url.Action("Index", "User")#forgotPass"> 忘记密码?</a>
                </label>

                <div class="registration">
                    没有账号?
                    <a class="" href="#">
                        创建账号
                    </a>
                </div>

            </div>
        </form>

        <!-- Modal -->
        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="forgotPass" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">忘记密码 ?</h4>
                    </div>
                    <div class="modal-body">
                        <p>输入您的注册账号.</p>
                        <input type="text" name="txtLoginName" placeholder="账号" autocomplete="off" class="form-control placeholder-no-fix" />
                        <p>输入您的注册邮箱，激活账号.</p>
                        <input type="text" name="email" placeholder="邮箱" autocomplete="off" class="form-control placeholder-no-fix" />

                    </div>
                    <div class="modal-footer">
                        <button data-dismiss="modal" class="btn btn-default" type="button">取消</button>
                        <button class="btn btn-success" type="button">提交</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- modal -->
    </div>


    @Scripts.Render("~/JS/Admin/jucheap/Login")
</body>
</html>

JuCheap.Web/Areas/Adm/Views/User/Reg.cshtml
@model dynamic
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<h2>title</h2>